<x-main-layout>
            <div class="relative px-6 lg:px-8 pt-16 pb-32">
                <div class="mx-auto max-w-screen-lg">
                    <h1 class="text-4xl font-bold tracking-tight pb-4 text-gray-900 sm:text-5xl">Charities</h1>
                    <p>All proceeds from Musicians on a Mission events are donated to small, local charities. In addition, donations of non-perishable food or other items are collected at all Musicians on a Mission events for community soup kitchens and food pantries.</p>
                    <div class="columns-1 md:columns-2 lg:columns-3 space-y-5 text-red-500 font-medium mt-10">
                        <div ><a href="http://180nj.org/" target="_blank">180 Turning Lives Around</a></div><p ><a href="http://www.asburyparkmusiclives.org/" target="_blank">Asbury Park Musical Heritage Fund</a></p><p ><a href="http://ashleylaurenfoundation.org/" target="_blank">Ashley Lauren Foundation</a></p><p ><a href="http://www.atonementlutheranchurch.com/foodpantry.htm" target="_blank">Atonement Lutheran Church Food Pantry</a></p><p ><a href="http://www.belmararts.org/">Belmar Arts Council</a><br></p><p ><a href="http://www.coastalhabitat.org/" target="_blank">Coastal Habitat for Humanity</a></p><p ><a href="http://collieryouthservicesch.ss8.sharpschool.com/" target="_blank">Collier House</a><br></p><p ><a href="http://www.newhopefoundation.org/" target="_blank">Epiphany House</a></p><p ><a href="https://familypromisemc.org/" target="_blank">Family Promise</a></p><p ><a href="http://www.411gina.org/" target="_blank">Gina for Missing Persons</a><br></p><p ><a href="https://www.habitatmonmouth.org/" target="_blank">Habitat for Humanity of Monmouth County</a></p><p ><a href="http://co.monmouth.nj.us/documents/41/Veterans%20Resource%20Guide%20%282%29.pdf" target="_blank">Homeless Veterans of Monmouth County</a></p><p ><a href="http://www.foodpantries.org/li/howell-emergency-food-pantry" target="_blank">Howell Emergency Food Pantry</a></p><p ><a href="http://www.joshuahouseministries.com/" target="_blank">Joshua House Ministries Food and Clothing Pantry</a></p><p ><a href="https://www.facebook.com/OceanNJ.TentCity.org" target="_blank">Lakewood Outreach Ministry</a></p><p ><a href="http://www.lightofday.org" target="_blank">Light of Day Foundation</a><br></p><p ><br></p><p ><br></p>
                    </div>
                </div>
            </div>
</x-main-layout>